Repository Argo-swe/argo-swe.github.io, pull requests merged in 2024-03, with the labels that each got.

#6 Verbali esterni firmati
  1 - Candidatura/Verbali/Esterni/VerbaleEsterno240311.pdf
  1 - Candidatura/Verbali/Esterni/VerbaleEsterno240312.pdf
Labels: Documentazione

#9 Link ai documenti della candidatura nella pagina web
  index.html
Labels: Documentazione

#12 Rename to LetteraDiCandidatura.pdf
  1 - Candidatura/LetteraDiCandidatura.pdf
Labels: bug

#13 Hotfix verbali interni con errori di compiler
  1 - Candidatura/Verbali/Interni/VerbaleInterno_240306.pdf
  1 - Candidatura/Verbali/Interni/VerbaleInterno_240307.pdf
  1 - Candidatura/Verbali/Interni/VerbaleInterno_240309.pdf
Labels: bug, HotFix

#14 Upgrade versioni e Reverse ordinamento
  index.html
Labels: enhancement, HotFix
